### ISSUE TITLE
Lang file not found (1.2.2)

### ISSUE THREAD

**Issue by stacmv** [aik27/inwidget#12]
After update to 1.2.2 I've encountered an error (require: file not found) in inWidget\Core class, line 284.

I had no time to discover, just commented lines 224-225:
$this->langPath = __DIR__.'/'.$this->langPath; // PHP < 5.6 fix
$this->cachePath = __DIR__.'/'.$this->cachePath; // PHP < 5.6 fix

In my case (PHP 5.5 оn linux and PHP 7.2 on windows) line 224 made langPath point to nonexistent directory (relative to index.php) 'classes/InWidget/langs/' instead of existing 'langs/'.

**Comment by aik27** [comment]
"langPath" and "cachePath" must be set manually in config.php or through the class constructor. Otherwise, widget will use default pattern: __DIR__.'/'.$this->langPath. So when you call the code from different directory or nesting level, this will cause an error.
