### ISSUE TITLE
Cache file contains plain text: ERROR #500: Account with this username does not exist

### ISSUE THREAD

**Issue by iBars** [aik27/inwidget#13]
Пишет эту ошибку на [сайте](https://mine.by) в блоке "Мы в соцсетях" (нажать значок Instagram). До недавнего времени все отлично работало. Была версия 1.1.6, обновился до последней, но все равно. На обеих версиях не работает.

**Comment by aik27** [comment]
"ERROR #500: Account with this username does not exist" исправляется версией 1.2.2. Сайт ваш не открывается. Больше нечего добавить. "На обеих версиях не работает" - это не баг репорт.

**Comment by vvzar** [comment]
Same error since 2019.08.06
Изменился API инсты?

**Comment by Mihail-Ttushkin** [comment]
> 
> 
> Пишет эту ошибку на [сайте](https://mine.by) в блоке "Мы в соцсетях" (нажать значок Instagram). До недавнего времени все отлично работало. Была версия 1.1.6, обновился до последней, но все равно. На обеих версиях не работает.

Такая же история) Не знаю что делать! Сайт https://strigi-art.ru/ в футере. Может кто подскажет, где копать?

**Comment by KolyambaBolotov** [comment]
Та же беда. На двух сайтах отвалился виджет.

**Comment by cabra** [comment]
Подтверждаю, еще на одном не работает.
https://karaoke-semenov.ru/gallery/
