### ISSUE TITLE
Нет доступа к изображениям

### ISSUE THREAD

**Issue by mnoskov** [aik27/inwidget#14]
Аккаунт: https://www.instagram.com/zegna_perm/

Api возвращает json со ссылками на изображения, доступа к которым нет. Хотя аккаунт доступен.

![- -1](https://user-images.githubusercontent.com/8789957/37814801-bc6f016e-2e8d-11e8-9edb-6bf011d0abf4.jpg)
![- -2](https://user-images.githubusercontent.com/8789957/37814800-bc4f1098-2e8d-11e8-9c1a-63b6b57a9fe6.jpg)
На аккаунте https://www.instagram.com/marinarinaldi_perm/ то же самое, но некоторые изображения доступны.

Что это такое может быть?

**Comment by aik27** [comment]
У инстаграм поменялся основной CDN сервер. А так как в библиотеке InstagramScraper жёстко зашиты адреса, это привело к тому, что вы видите. В новой версии виджета будет исправление.

**Comment by dmi3yy** [comment]
в 1.2.3 все точно так же

**Comment by dmi3yy** [comment]
Так же получил токен и прописал но это тоже не помогло

**Comment by mnoskov** [comment]
В моем случае обновление помогло

**Comment by dmi3yy** [comment]
Все мой косяк не там кеш почистил, работает
