### ISSUE TITLE
Ошибка 429 Page not found

### ISSUE THREAD

**Issue by mnoskov** [aik27/inwidget#16]
На нескольких аккаунтах такая ошибка, в кеше текст, похоже на исходник страницы. Очистка кеша не помогает.

<img src="https://monosnap.com/file/ZJti6xXO7IBEe3GTfr5BA3sKYygw9j.png">

Как вариант, может быть будет лучше при неверном ответе сервера не обновлять кеш, а логировать ошибку? Так хоть виджет продолжит показывать изображения, хоть и, возможно, не актуальные.

**Comment by aik27** [comment]
HTTP ошибка под номером 429 означает Too Many Requests (cлишком много запросов). Дискуссия развернулась здесь https://github.com/postaddictme/instagram-php-scraper/issues/319
По поводу старого кэша, это потребует переписать чуть ли не всю логику. Как вариант, можете просто установить срок обновления кэша в несколько лет, пока не появится стабильная версия.
