### ISSUE TITLE
ERROR #500: Invalid ACCESS TOKEN

### ISSUE THREAD

**Issue by vosur** [aik27/inwidget#17]
Привет! Сегодня утром появилась ошибка виджета:

> ERROR #500: Invalid ACCESS TOKEN. Server answer: {"meta": {"code": 400, "error_type": "APINotAllowedError", "error_message": "This endpoint has been retired"}}

Уже несколько раз выдавал себе новый TOKEN, удалял кэш - безрезультатно. Может instagram опять что-то выдумали?

**Comment by aik27** [comment]
04 апреля официальное API отключили

**Comment by vosur** [comment]
В 2020 году обещали же? 
А что теперь делать? Есть варианты использования виджета?

**Comment by aik27** [comment]
У виджета есть альтернативное API на основе instagram-php-scraper. Достаточно поставить последнюю версию и не указывать ACCESS_TOKEN.

В целом ситуация сейчас такая:

Instagram лихорадит от безумного количества обнов и резких телодвижений руководства. Чтобы поддерживать совместимость, только с начала марта мной было выпущено уже 5 версий виджета.

МОЙ ВАМ СОВЕТ:

1. Обновитесь до последней версии с нуля. На сегодняший день это 1.2.5.
2. Убедитесь, что всё работает.
3. Задайте в настройках параметру cacheExpiration значение 70000 часов.

Да, при таком большом значении срока действия кэша виджет не будет обновлять статистику и список фотографий, но хотя бы будет работать. Советую именно таким образом переждать этот период, пока всё не утрясётся.

**Comment by vosur** [comment]
Спасибо! Я заметил, что вы оперативно обновляете свой виджет. Сейчас последую совету. 
Единственная просьба: если будет возможно, отпишитесь в этой ветке, когда проблема будет решена. Спасибо
