### ISSUE TITLE
Не добавлять в кеш данные если запрос вернулся с ошибкой

### ISSUE THREAD

**Issue by RuZniki** [aik27/inwidget#18]
На одном сайте, у меня возникла проблема.
Я настроил скрипт и всё отлично работает, но через время возникает ошибка при обновление.
Т.е. запрос выполняется с ошибкой.

После этого вместо рабочего виджета на сайте я получаю инфу об ошибке.

Предложение: если в кеше уже есть данные, то если при обновление запрос прошел с ошибкой, оставляем старую версию.

**Comment by aik27** [comment]
Реализованно в 1.2.6
