### ISSUE TITLE
Добавить поддержку composer'a

### ISSUE THREAD

**Issue by sw4n** [aik27/inwidget#6]
Привет! Хороший виджет, давно пользуюсь, и даже сделал себе отдельный репозиторий с этим кодом, но есть просьба. 
Добавьте пожалуйста composer.json файл, для того чтобы можно было устанавливать код через composer. Для php developer'ов это уже давно стандарт для использования, и думаю в каждом современном проекте он есть. Рекомендую также добавить репозиторий на packagist. Заодно можно будет отслеживать сколько людей его установило, ну и может быть добавиться звёздочек на github ;)
В общем сделать надо что-то наподобие такого
https://github.com/sw4n/inwidget/blob/master/composer.json
могу также законтрибьютить и скинуть на Вас pull request с моего форка с изменением.

**Comment by pomerla** [comment]
Привет.
sw4n дело говорит. composer.json в студию. 
Создайте ветку для дополнения, языковые файлы + прочее...

**Comment by gserrg** [comment]
@sw4n абсолютно поддерживаю, охр*нел, увидев этот виджет установленный коллегами тупо копипастом :face_with_head_bandage:

**Comment by aik27** [comment]
Эксперты по composer. К вам вопрос. 
Добавил я composer.json и разместил пакет на packagist.org. 
Как победить эту ошибку при инсталяции пакета?
```
[InvalidArgumentException]
Could not find package aik27/inwidget at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```
В composer.json прописаны директивы:

"minimum-stability": "dev",
"prefer-stable": true

Предполагаю, что после размещения стабильной версии в релизах ошибка уйдёт, но всё же?

**Comment by dmi3yy** [comment]
Да все верну нужно после размещения файла зарелизить версию

+ нужно связать пакажист и гитхаб что б оно автоматом работало

**Comment by aik27** [comment]
Готово. Можно ставить командой:
``` 
composer require aik27/inwidget
```

**Comment by sw4n** [comment]
@aik27 спасибо большое :) Вы сделали некоторое количество людей счастливыми! Закрываю issue.
