### ISSUE TITLE
Конфиг через конструктор

### ISSUE THREAD

**Issue by mihdan** [aik27/inwidget#8]
Александр, добавьте, пожалуйста, возможность передавать конфиг в качестве параметра для конструктора класса `$inWidget = new inWidget( $config );` или метод типа `$inWidget->setOption( 'login', 'mihdan' );`.

Соответственно, дефолтные настройки внести в сам класс и перезаписывать теми, что переданы в конструктор или через метод `setOption()`

Тогда ваш проект можно будет интегрировать в любой другой, я использую его для создания виджета в WordPress, например.

Спасибо

**Comment by mihdan** [comment]
Сам плагин выложил [тут](https://github.com/mihdan/mihdan-inwidget)

**Comment by aik27** [comment]
Спасибо за предложение. Добавлю в 1.1.3
